source 'https://rubygems.org'
ruby '2.1.1'
gem 'rails', '4.1.7'
gem 'mysql2'

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails', '3.1'
gem 'jquery-ui-rails', '4.1.0'
gem 'jquery-ui-themes'
gem 'jbuilder', '~> 1.2'
gem 'execjs', :group => :production
gem 'therubyracer', :group => :production

gem 'acts-as-taggable-on'
gem 'cancan'
gem 'capistrano', '~> 3.1.0'
gem 'capistrano-rails', '~> 1.1.0'
gem 'capistrano-rvm'
gem 'capistrano-bundler'
gem 'carrierwave'
gem 'closure_tree'
gem 'ckeditor'
gem 'country_select'
gem 'devise'
gem 'devise-encryptable'
gem 'etherpad-lite'
gem 'event-calendar', :require => 'event_calendar'
gem 'feedjira'
gem 'figaro'
gem 'flickraw'
gem 'fog'
gem 'font-awesome-rails'
gem 'formtastic'
gem 'foundation-rails', '5.3.0'
gem 'friendly_id' , '~> 5.0.0'
gem 'friendly_id-globalize'
gem 'geocoder'
gem 'globalize', github: 'globalize/globalize', branch: 'master'
gem 'haml-rails'
gem 'handles_sortable_columns'
gem 'has_scope'
gem 'hpricot'
gem 'http_accept_language'
gem 'inherited_resources', github: 'josevalim/inherited_resources'
gem 'kaminari'
gem 'metamagic'
gem 'mini_magick'
gem 'nested_form'
# gem 'net-ssh', '~> 2.8.1', :git => "https://github.com/net-ssh/net-ssh"
gem 'oauth-client'
gem 'omniauth-facebook' #, '1.4.0'
gem 'omniauth-google-oauth2'
gem 'omniauth-twitter'
gem 'paper_trail', '>= 3.0.0.rc1'
gem 'rails3-jquery-autocomplete', github: 'cenotaph/rails3-jquery-autocomplete', branch: 'master'
gem 'randumb'
gem 'recaptcha'
gem 'rolify'
gem 'soundmanager2-rails'
gem 'thinking-sphinx', '3.1.0'
gem 'truncate_html'
gem 'twitter', '5.6.0'
gem 'unicorn'
gem 'unf' 
gem 'vimeo'


group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'html2haml'
  gem 'hub', :require=>nil
  gem 'letter_opener'
  gem 'nifty-generators'
  gem 'rails-footnotes',  '>= 3.7.9'
  gem 'quiet_assets'
  gem 'rb-fchange', :require=>false
  gem 'rb-fsevent', :require=>false
  gem 'rb-inotify', :require=>false
end
group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
end
group :test do
  gem 'faker'
  gem 'capybara'
  gem 'database_cleaner', '1.0.1'
  gem 'email_spec'
end
