source 'https://rubygems.org'
ruby '2.5.3'
gem 'rails', '5.2.2'
gem 'mysql2'

gem 'sass-rails'
gem 'uglifier'
# gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jquery-ui-themes'
gem 'jbuilder'
# gem 'execjs', :group => :production
gem 'activemodel-serializers-xml'
gem 'acts-as-taggable-on', '~> 6.0'
gem "bulma-rails", "~> 0.7.2"
gem 'cancan'
gem 'capistrano'#, '3.6.1'
gem 'capistrano-rails'#, '~> 1.1.0'
gem 'capistrano-rvm'
gem 'capistrano-bundler'
gem 'capistrano3-puma'
gem 'carrierwave'
gem 'carrierwave-aws'
gem 'closure_tree'
gem 'ckeditor'#, '4.1.2'
gem 'country_select'
gem 'devise'#, github: 'plataformatec/devise', branch: :master
gem 'devise-encryptable'
gem 'etherpad-lite'
gem 'event-calendar', :require => 'event_calendar'
gem 'feedjira'
gem 'figaro'
gem 'flickraw'
# gem 'fog'
gem 'font-awesome-rails'
gem 'formtastic'
# gem 'foundation-rails'
gem 'friendly_id' #, '~> 5.0.0'
# gem 'friendly_id-globalize'
gem 'geocoder'
# gem 'globalize', git: 'https://github.com/globalize/globalize'
gem 'haml-rails'
gem 'handles_sortable_columns'
gem 'has_scope'
gem 'hpricot'
gem 'http', '~> 0.6.0'
gem 'http_accept_language'
gem 'jquery-slick-rails'
# gem 'inherited_resources', github: 'josevalim/inherited_resources'
gem 'kaminari'
gem 'mediaelement_rails'
gem 'meta-tags', require: 'meta_tags'
gem 'mini_magick'
gem 'nested_form'
# gem 'net-ssh', '~> 2.8.1', :git => "https://github.com/net-ssh/net-ssh"
gem 'oauth-client'
gem 'omniauth-facebook' #, '1.4.0'
gem 'omniauth-google-oauth2'
gem 'omniauth-twitter'
# gem 'paper_trail', '>= 3.0.0.rc1'
gem 'rails4-autocomplete'
#gem 'rails3-jquery-autocomplete', github: 'cenotaph/rails3-jquery-autocomplete', branch: 'master'
gem 'randumb'
gem "recaptcha", '3.0', require: "recaptcha/rails"
gem 'rolify'
gem 'rollbar'
gem 'rspec-core'
gem 'rubocop-rspec'
gem 'thinking-sphinx'
gem 'truncate_html'
gem 'twitter'
gem 'unicorn'
gem 'unf'
gem 'vimeo'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'html2haml'
  gem 'hub', :require=>nil
  gem 'letter_opener'
  gem 'nifty-generators'
  gem 'rb-fchange', :require=>false
  gem 'rb-fsevent', :require=>false
  gem 'rb-inotify', :require=>false
end
group :development, :test do
  gem 'rspec-rails', '~> 3.5'
  gem 'bullet'
end
group :test do
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'shoulda-matchers', '~> 3.1'
  gem 'simplecov', require: false
  gem 'webmock'
end
